language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t yassinekhouaja/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yassinekhouaja/react-test npm test

after_success:
  - docker build -t yassinekhouaja/multi-client ./client
  - docker build -t yassinekhouaja/multi-nginx ./nginx
  - docker build -t yassinekhouaja/multi-server .server
  - docker build -t yassinekhouaja/multi- ./
